### ISSUE TITLE
pom compiler.source 1.7

### ISSUE THREAD

**Issue by RMiB** [orientechnologies/spring-data-orientdb#72]
In pom files compiler.source is 1.7:
```
<maven.compiler.source>1.7</maven.compiler.source>
<maven.compiler.target>1.7</maven.compiler.target>
```

But the code uses things introduced only in 1.8:
java.util.Spliterator - https://docs.oracle.com/javase/8/docs/api/java/util/Spliterator.html  -
 since: 1.8

**Comment by laa** [comment]
which version is it ?

**Comment by RMiB** [comment]
version 0.13 using jitpack (https://jitpack.io/#orientechnologies/spring-data-orientdb)
It uses source, target to determine the version of the compiler java

Error build using Java version: 1.7.0_76, vendor: Oracle Corporation:
https://jitpack.io/com/github/orientechnologies/spring-data-orientdb/0.13/build.log

```
[ERROR] /home/jitpack/build/spring-data-orientdb-commons/src/main/java/org/springframework/data/orient/commons/repository/query/OrientParameters.java:[11,17] cannot find symbol
  symbol:   class Spliterator
  location: package java.util
```

**Comment by robfrank** [comment]
thank you very much for your report. The code was written by the original contributor, and I use to compile with jdk8, so I never get aware of it. Let me check what to do.

**Comment by robfrank** [comment]
ported to java8.
